apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  MYSQL_DB: messaging_db
  MYSQL_USER: user
  MYSQL_HOST: mysql

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: strongpassword
  MYSQL_ROOT_PASSWORD: rootpassword

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
  labels:
    app: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: django-container
          image: yourdockerhub/messaging-app:v1
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: MYSQL_USER
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: MYSQL_HOST
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service
spec:
  selector:
    app: messaging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
